[mcp_servers.github]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]
env = { "GITHUB_PERSONAL_ACCESS_TOKEN" = "value" }
[mcp_servers.qiita]
command = "npx"
args = ["-y", "@2bo/qiita-mcp-server"]
env = { "QIITA_API_TOKEN" = "value" }
[sandbox]
mode = "workspace-write"
writable_roots = [
    "/tmp",
]
network_access = false  # Like read-only, this also defaults to false and can be omitted.
